### ISSUE TITLE
Train on a Custom Dataset

### ISSUE THREAD

**Issue by pranay-ar** [carlossantosgarcia/few-shot-classification#2]
Hi, thank you for your interesting work. I wanted to implement the code on my dataset which is having around 1000 images from 200 classes. Though I understood the flow of the model, I am not sure about the structure of the dataset. It would be really helpful to make the dataset and CSV files public to understand the structure of the dataset so that it is easy to train it on custom data. Thank you!

**Comment by carlossantosgarcia** [comment]
Hi Pranay, I'll soon upload a snippet of some of our csv files. The data on which we trained our models is however not public, but the csv structure will help you understand how our code can be applied to new images.

**Comment by carlossantosgarcia** [comment]
I have uploaded a new and cleaner version of our implementation of Siamese networks for contrastive loss, that should help you to adapt it to your work. The same structure can be applied to triplet loss. The example csv is also available in the data folder.
